package:
  name: ahoproc_tools
  version: "1.0.0"

source:
  git_rev: "e707e34"
  git_url: https://github.com/santi-pdp/ahoproc_tools.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - six
    - scikit-learn

about:
  home: https://github.com/santi-pdp/ahoproc_tools
  license: BSD
  license_file: LICENSE
  summary: Ahocoder processing tools